---

- name: Configure postfix debconf type
  debconf: name='postfix'
           question='postfix/main_mailer_type'
           vtype='string'
           value='Internet Site'

- name: Configure postfix debconf domain name
  debconf: name='postfix'
           question='postfix/mailname'
           vtype='string'
           value='{{postfix_mail_domains[0]}}'

- name: Install postfix packages
  apt:
    name: postfix
    state: 'present'

- name: Add TLS config for outgoing connections
  lineinfile:
    dest:  "/etc/postfix/main.cf"
    line:  "smtp_tls_security_level=may"
    regexp: "^smtp_tls_security_level"
    insertafter: "EOF"    
  notify: reload postfix

- name: Add TLS config for ingoing connections
  lineinfile:
    dest:  "/etc/postfix/main.cf"
    line:  "smtpd_tls_security_level=may"
    regexp: "^smtpd_tls_security_level"
    insertafter: "EOF"
  notify: reload postfix

- name: Use file for mydestinations
  lineinfile:
    dest:  "/etc/postfix/main.cf"
    line:  "mydestination = hash:/etc/postfix/destinations"
    regexp: "^mydestination"
  notify: reload postfix

- name: Set myhostname in main.cf
  lineinfile:
    dest:  "/etc/postfix/main.cf"
    line:  "myhostname = {{ postfix_myhostname }}"
    regexp: "^myhostname"
  notify: reload postfix

- name: Add config for virtual_alias_maps
  lineinfile:
    dest:  "/etc/postfix/main.cf"
    line:  "virtual_alias_maps = hash:{{ postfix_virtual_alias_maps_file }}"
    regexp: "^virtual_alias_maps"
    insertafter: "EOF"
  notify: reload postfix

- name: Add postfix domains to destinations
  lineinfile:
    dest:  "/etc/postfix/destinations"
    line:  "{{ item }} OK"
    regexp: "^{{ item }}"
    insertafter: "EOF"
    owner:  "root"
    group:  "root"
    mode:   "0640"
    create: "yes"
  with_items: '{{ postfix_mail_domains }}'
  register: postfix_dest_file

- name: Add local domain to destinations
  lineinfile:
    dest:  "/etc/postfix/destinations"
    line:  "localhost OK"
    regexp: "^localhost"
    insertafter: "EOF"
  register: postfix_dest_file_local

- name: Add rules to virtual_alias_maps
  lineinfile:
    dest:  "{{ postfix_virtual_alias_maps_file }}"
    line:  "{{ item.match }} {{ item.dest }}"
    regexp: "^{{ item.match }}"
    insertafter: "EOF"
    owner:  "root"
    group:  "root"
    mode:   "0640"
    create: "yes"
  with_items: '{{ postfix_virtual_alias_maps }}'
  register: postfix_virtual_alias_maps_file_result

- name: Run postmap for the destination file
  command: "postmap /etc/postfix/destinations"
  notify: reload postfix
  when: postfix_dest_file.changed or postfix_dest_file_local.changed

- name: Run postmap for the virtual_alias_maps file
  command: "postmap {{ postfix_virtual_alias_maps_file }}"
  notify: reload postfix
  when: postfix_virtual_alias_maps_file_result.changed
