---

- name: Configure postfix debconf
  debconf: name='postfix'
           question='{{ item.key }}'
           vtype='string'
           value='{{ item.value }}'
  with_dict:
    postfix/main_mailer_type: 'Internet Site'
    postfix/mailname: '{{postfix_mail_domain}}'

- name: Install postfix packages
  apt:
    name: '{{ item }}'
    state: 'present'
  with_items:
  - postfix

- name: Add TLS config for outgoing connections
  lineinfile:
    dest:  "/etc/postfix/main.cf"
    line:  "smtp_tls_security_level=may"
    regexp: "^smtp_tls_security_level"
    insertafter: "EOF"    

- name: Add TLS config for ingoing connections
  lineinfile:
    dest:  "/etc/postfix/main.cf"
    line:  "smtpd_tls_security_level=may"
    regexp: "^smtpd_tls_security_level"
    insertafter: "EOF"
