---

- name: Configure postfix debconf type
  debconf: name='postfix'
           question='postfix/main_mailer_type'
           vtype='string'
           value='Internet Site'

- name: Configure postfix debconf domain name
  debconf: name='postfix'
           question='postfix/mailname'
           vtype='string'
           value='{{postfix_mail_domain}}'

- name: Install postfix packages
  apt:
    name: postfix
    state: 'present'

- name: Add TLS config for outgoing connections
  lineinfile:
    dest:  "/etc/postfix/main.cf"
    line:  "smtp_tls_security_level=may"
    regexp: "^smtp_tls_security_level"
    insertafter: "EOF"    

- name: Add TLS config for ingoing connections
  lineinfile:
    dest:  "/etc/postfix/main.cf"
    line:  "smtpd_tls_security_level=may"
    regexp: "^smtpd_tls_security_level"
    insertafter: "EOF"

- name: Use file for mydestinations
  lineinfile:
    dest:  "/etc/postfix/main.cf"
    line:  "mydestination = hash:/etc/postfix/destinations"
    regexp: "^mydestination"

- name: Add postfix domain to destinations
  lineinfile:
    dest:  "/etc/postfix/destinations"
    line:  "{{ item }} OK"
    regexp: "^{{ item }}"
    insertafter: "EOF"
    owner:  "root"
    group:  "root"
    mode:   "0640"
    create: "yes"
  with_items: '{{ postfix_mail_domains }}'
  register: postfix_dest_file

- name: Add local domain to destinations
  lineinfile:
    dest:  "/etc/postfix/destinations"
    line:  "localhost OK"
    regexp: "^localhost"
    insertafter: "EOF"
  register: postfix_dest_file_local

- name: Run postmap for the destination file
  command: "postmap /etc/postfix/destinations"
  notify: reload postfix
  when: postfix_dest_file.changed or postfix_dest_file_local.changed
